# @Service: Dynamo
# @Version: 1.0

service: portafolio-dynamodb

functions:
  createUser:
    handler: dist/createUser.handler
    environment:
      LABEL: 'Create User'
    events:
      - http:
          path: /
          method: POST

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

custom:
  stage: ${opt:stage, self:provider.stage}
  type: ${env:type, 'primary'}

  serverless-dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      docker: false
      port: 8000
      inMemory: true
      migrate: true
      convertEmptyValues: true

package:
  patterns:
    - '!src/**'
    - '!node_modules/**'
    - '!node_modules/@portafolio/libs/node_modules/.prisma/client/libquery_engine-*'
    - '!node_modules/@portafolio/libs/node_modules/prisma/libquery_engine-*'
    - '!node_modules/@portafolio/libs/node_modules/@prisma/engines/**'
    - '**/*.prisma'
    - '**/libquery_engine-rhel-openssl-1.0.x.so.node'
    - 'node_modules/@portafolio/libs/node_modules/@prisma/client/**'
    - 'node_modules/@portafolio/libs/node_modules/.prisma/client/index.js'
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs18.x
  endpointType: regional
  stage: dev
  region: ${opt:region, 'us-east-2'}
  timeout: 30
  logRetentionInDays: 60
  versionFunctions: false

  environment:
    STAGE: ${self:custom.stage}
    SERVICE: dynamodb
    REGION: ${self:provider.region}
    MONGO_ENCRYPTION_KEY: k1.aesgcm256.3Y7Plme6ZAbCBQdVo3mM15x5A79un8KKXDaqjfhZ8lM=

  apiGateway:
    shouldStartNameWithService: true
  deploymentBucket:
    name: com.ale-portafolio.${self:provider.region}.${self:custom.stage}.deploys

resources:
  Resources:
    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
